name: Upload mirai build artifacts
author: Karlatemp
description: Not exists

runs:
  using: composite
  steps:
    - name: Ensure build
      shell: bash
      run: >
        ./gradlew build publishToMavenLocal --scan
        --exclude-task allTests
        --exclude-task jvmTest
        --exclude-task androidTest
        --exclude-task test
        --exclude-task check

    - name: Upload mirai-core-utils
      uses: actions/upload-artifact@v3
      with:
        name: mirai-core-utils
        path: mirai-core-utils/build/libs

    - name: Upload mirai-core-utils-barcode
      uses: actions/upload-artifact@v3
      with:
        name: mirai-core-utils-barcode
        path: mirai-core-utils-barcode/build/libs

    - name: Upload mirai-core-api
      uses: actions/upload-artifact@v3
      with:
        name: mirai-core-api
        path: mirai-core-api/build/libs

    - name: Upload mirai-core
      uses: actions/upload-artifact@v3
      with:
        name: mirai-core
        path: mirai-core/build/libs

    - name: Upload mirai-core-all
      uses: actions/upload-artifact@v3
      with:
        name: mirai-core-all
        path: mirai-core-all/build/libs


    - name: Upload mirai-console
      uses: actions/upload-artifact@v3
      with:
        name: mirai-console
        path: mirai-console/backend/mirai-console/build/libs

    - name: Upload mirai-console-terminal
      uses: actions/upload-artifact@v3
      with:
        name: mirai-console-terminal
        path: mirai-console/frontend/mirai-console-terminal/build/libs


    - name: Upload mirai-console-gradle
      uses: actions/upload-artifact@v3
      with:
        name: mirai-console-gradle
        path: mirai-console/tools/gradle-plugin/build/libs

