/*
 * Copyright 2020 Mamoe Technologies and contributors.
 *
 * 此源代码的使用受 GNU AFFERO GENERAL PUBLIC LICENSE version 3 许可证的约束, 可以在以下链接找到该许可证.
 * Use of this source code is governed by the GNU AGPLv3 license that can be found through the following link.
 *
 * https://github.com/mamoe/mirai/blob/master/LICENSE
 */

package net.mamoe.mirai.console.setting

import kotlinx.serialization.KSerializer
import kotlin.properties.ReadWriteProperty
import kotlin.reflect.KProperty

/**
 * !!! This file is auto-generated by backend/codegen/src/main/kotlin/net.mamoe.mirai.console.codegen.ValuesCodegen.kt
 * !!! for better performance
 * !!! DO NOT MODIFY THIS FILE MANUALLY
 */

sealed class Value<T : Any> : ReadWriteProperty<Setting, T> {
    abstract var value: T

    /**
     * 用于更新 [value] 的序列化器
     */
    abstract val serializer: KSerializer<T>
    override fun getValue(thisRef: Setting, property: KProperty<*>): T = value
    override fun setValue(thisRef: Setting, property: KProperty<*>, value: T) {
        this.value = value
    }

    override fun equals(other: Any?): Boolean {
        if (other == null) return false
        if (other::class != this::class) return false
        other as Value<*>
        return other.value == this.value
    }

    override fun hashCode(): Int = value.hashCode()
}

sealed class PrimitiveValue<T : Any> : Value<T>()

sealed class NumberValue<T : Number> : Value<T>()
abstract class IntValue internal constructor() : NumberValue<Int>()
abstract class ShortValue internal constructor() : NumberValue<Short>()
abstract class ByteValue internal constructor() : NumberValue<Byte>()
abstract class LongValue internal constructor() : NumberValue<Long>()
abstract class FloatValue internal constructor() : NumberValue<Float>()
abstract class DoubleValue internal constructor() : NumberValue<Double>()

abstract class BooleanValue internal constructor() : PrimitiveValue<Boolean>()
abstract class CharValue internal constructor() : PrimitiveValue<Char>()
abstract class StringValue internal constructor() : PrimitiveValue<String>()

// T can be primitive array or typed Array 
sealed class ArrayValue<T : Any> : Value<T>()
sealed class PrimitiveArrayValue<T : Any> : ArrayValue<T>()

abstract class IntArrayValue internal constructor() : PrimitiveArrayValue<IntArray>(), Iterable<Int> {
    override fun iterator(): Iterator<Int> = this.value.iterator()
}

abstract class ShortArrayValue internal constructor() : PrimitiveArrayValue<ShortArray>(), Iterable<Short> {
    override fun iterator(): Iterator<Short> = this.value.iterator()
}

abstract class ByteArrayValue internal constructor() : PrimitiveArrayValue<ByteArray>(), Iterable<Byte> {
    override fun iterator(): Iterator<Byte> = this.value.iterator()
}

abstract class LongArrayValue internal constructor() : PrimitiveArrayValue<LongArray>(), Iterable<Long> {
    override fun iterator(): Iterator<Long> = this.value.iterator()
}

abstract class FloatArrayValue internal constructor() : PrimitiveArrayValue<FloatArray>(), Iterable<Float> {
    override fun iterator(): Iterator<Float> = this.value.iterator()
}

abstract class DoubleArrayValue internal constructor() : PrimitiveArrayValue<DoubleArray>(), Iterable<Double> {
    override fun iterator(): Iterator<Double> = this.value.iterator()
}

abstract class BooleanArrayValue internal constructor() : PrimitiveArrayValue<BooleanArray>(), Iterable<Boolean> {
    override fun iterator(): Iterator<Boolean> = this.value.iterator()
}

abstract class CharArrayValue internal constructor() : PrimitiveArrayValue<CharArray>(), Iterable<Char> {
    override fun iterator(): Iterator<Char> = this.value.iterator()
}


sealed class TypedPrimitiveArrayValue<E> : ArrayValue<Array<E>>(), Iterable<E> {
    override fun iterator() = this.value.iterator()
}

abstract class TypedIntArrayValue internal constructor() : TypedPrimitiveArrayValue<Int>()
abstract class TypedShortArrayValue internal constructor() : TypedPrimitiveArrayValue<Short>()
abstract class TypedByteArrayValue internal constructor() : TypedPrimitiveArrayValue<Byte>()
abstract class TypedLongArrayValue internal constructor() : TypedPrimitiveArrayValue<Long>()
abstract class TypedFloatArrayValue internal constructor() : TypedPrimitiveArrayValue<Float>()
abstract class TypedDoubleArrayValue internal constructor() : TypedPrimitiveArrayValue<Double>()
abstract class TypedBooleanArrayValue internal constructor() : TypedPrimitiveArrayValue<Boolean>()
abstract class TypedCharArrayValue internal constructor() : TypedPrimitiveArrayValue<Char>()
abstract class TypedStringArrayValue internal constructor() : TypedPrimitiveArrayValue<String>()

sealed class ListValue<E> : Value<List<E>>(), List<E>
abstract class IntListValue internal constructor() : ListValue<Int>()
abstract class ShortListValue internal constructor() : ListValue<Short>()
abstract class ByteListValue internal constructor() : ListValue<Byte>()
abstract class LongListValue internal constructor() : ListValue<Long>()
abstract class FloatListValue internal constructor() : ListValue<Float>()
abstract class DoubleListValue internal constructor() : ListValue<Double>()
abstract class BooleanListValue internal constructor() : ListValue<Boolean>()
abstract class CharListValue internal constructor() : ListValue<Char>()
abstract class StringListValue internal constructor() : ListValue<String>()

abstract class SettingListValue<T : Setting> internal constructor() : Value<List<T>>(), List<T>

sealed class SetValue<E> : Value<Set<E>>(), Set<E>
abstract class IntSetValue internal constructor() : SetValue<Int>()
abstract class ShortSetValue internal constructor() : SetValue<Short>()
abstract class ByteSetValue internal constructor() : SetValue<Byte>()
abstract class LongSetValue internal constructor() : SetValue<Long>()
abstract class FloatSetValue internal constructor() : SetValue<Float>()
abstract class DoubleSetValue internal constructor() : SetValue<Double>()
abstract class BooleanSetValue internal constructor() : SetValue<Boolean>()
abstract class CharSetValue internal constructor() : SetValue<Char>()
abstract class StringSetValue internal constructor() : SetValue<String>()

abstract class SettingSetValue<T : Setting> internal constructor() : Value<Set<T>>(), Set<T>

abstract class SettingValue<T : Setting> internal constructor() : Value<T>()

abstract class MutableListValue<T : Any> internal constructor() : Value<MutableList<Value<T>>>(), MutableList<T>

abstract class MutableIntListValue internal constructor() : Value<MutableList<Int>>(), MutableList<Int>
abstract class MutableShortListValue internal constructor() : Value<MutableList<Short>>(), MutableList<Short>
abstract class MutableByteListValue internal constructor() : Value<MutableList<Byte>>(), MutableList<Byte>
abstract class MutableLongListValue internal constructor() : Value<MutableList<Long>>(), MutableList<Long>
abstract class MutableFloatListValue internal constructor() : Value<MutableList<Float>>(), MutableList<Float>
abstract class MutableDoubleListValue internal constructor() : Value<MutableList<Double>>(), MutableList<Double>
abstract class MutableBooleanListValue internal constructor() : Value<MutableList<Boolean>>(), MutableList<Boolean>
abstract class MutableCharListValue internal constructor() : Value<MutableList<Char>>(), MutableList<Char>
abstract class MutableStringListValue internal constructor() : Value<MutableList<String>>(), MutableList<String>

abstract class MutableSettingListValue<T : Setting> internal constructor() : Value<MutableList<T>>(), MutableList<T>

abstract class MutableSetValue<T : Any> internal constructor() : Value<MutableSet<Value<T>>>(), MutableSet<T>

abstract class MutableIntSetValue internal constructor() : Value<MutableSet<Int>>(), MutableSet<Int>
abstract class MutableShortSetValue internal constructor() : Value<MutableSet<Short>>(), MutableSet<Short>
abstract class MutableByteSetValue internal constructor() : Value<MutableSet<Byte>>(), MutableSet<Byte>
abstract class MutableLongSetValue internal constructor() : Value<MutableSet<Long>>(), MutableSet<Long>
abstract class MutableFloatSetValue internal constructor() : Value<MutableSet<Float>>(), MutableSet<Float>
abstract class MutableDoubleSetValue internal constructor() : Value<MutableSet<Double>>(), MutableSet<Double>
abstract class MutableBooleanSetValue internal constructor() : Value<MutableSet<Boolean>>(), MutableSet<Boolean>
abstract class MutableCharSetValue internal constructor() : Value<MutableSet<Char>>(), MutableSet<Char>
abstract class MutableStringSetValue internal constructor() : Value<MutableSet<String>>(), MutableSet<String>

abstract class MutableSettingSetValue<T : Setting> internal constructor() : Value<MutableSet<T>>(), MutableSet<T>


/**
 * 只引用这个对象, 而不跟踪其成员.
 * 仅适用于基础类型, 用于 mutable list/map 等情况; 或标注了 [Serializable] 的类.
 */
abstract class DynamicReferenceValue<T : Any> internal constructor() : Value<T>()
