name: mirai-doc Publish

on:
  push:
    tags:
      - 'v*' # 正式版本


jobs:
  mirai-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Checkout submodules
        run: git submodule update --init --recursive

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: chmod -R 777 *
        run: chmod -R 777 *

      - name: Prepare environment
        run: ./gradlew :mirai-dokka:prepare

      - name: Dokka
        run: ./gradlew dokkaHtmlMultiModule

      - name: Update version number
        run: ./gradlew :mirai-dokka:update-vers

      - name: Deploy
        run: ./gradlew :mirai-dokka:deployPages
        env:
          gh_token: ${{ secrets.MAMOE_TOKEN }}
